# Generated by Django 5.0 on 2024-08-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_VNPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('oder_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('vnp_TransactionNo', models.CharField(blank=True, max_length=100, null=True)),
                ('vnp_ResponseCode', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
